### ISSUE TITLE
CSS overflow: hidden 

### ISSUE THREAD

**Issue by sheisJin** [sheisJin/Document#4]
### 이슈 내용

1. 버튼 hover시 툴팁이 노출 되는 기능이 있는데, IE에서 hover시 툴팁이 노출 되지 않음.
2. 버튼 아이콘 위에 new 아이콘을 추가하는데, IE에서 new 아이콘이 짤려서 노출 되는 이슈.

### 해결 방법

1. hover시 overflow 속성 변경하여 툴팁 노출 될 수 있도록 수정 
```scss
button  {
     &:hover {
          // IE는 overflow: hidden이 기본 값으로 되어 있으며, IE10 에서는 툴팁이 버튼 영역을 확장하고 있기 때문에
          // 기본 상태는 overflow: hidden, 마우스 오버 하면 overflow: visible로 하여 ie10에서 툴팁이 클릭영역을 가리지 않고, 
          // 마우스 오버 했을 때 툴팁이 표현 되도록 수정 함
          overflow: visible;
     }
}
```

2. 버튼 아이콘에 overflow: visible 속성을 추가하여 new 아이콘이 짤리지 않도록 수정
